version: "2.3"
services:
  web:
    image: hb-vendor
    container_name: hb_vendor_api
    ports:
      - 8080:9090
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./config/config_dev.yml:/app/config_dev.yml
  mysql:
    image: mysql:5.7 
    container_name: hb_vendor_mysql
    command: mysqld --user=root
#    volumes:
#      - ./hb_vendor.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3310:3306
    environment:
      - MYSQL_DATABASE=huobi_vendors
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    #docker exec -it f-mysql /bin/bash
    #mysql -u root -p
    #GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';
    #FLUSH PRIVILEGES