database:
  user: user
  password: password
  net: tcp
  host: 127.0.0.1
  name: article
  port: 3306
  allowNativePasswords: true
  params:
    parseTime: "true"
    timeZone: "Asia/Shanghai"
redis:
  host: 127.0.0.1
  port: 6739
  password: ""
  db: 0
server:
  address: ":9090"
