database:
  user: user
  password: password
  net: tcp
  host: 127.0.0.1
  name: huobi_vendors
  port: 3310
  allowNativePasswords: true
  params:
    parseTime: "true"
    timeZone: "Asia/Shanghai"
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
server:
  address: ":8080"
debug: true